name: Datree Analysis

on:
  push:
    branches: [ "main" ]
    paths: ["kubernetes"]
  pull_request:
    branches: [ "main" ]
    paths: ["kubernetes"]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Datree CLI
        uses: datreeio/action-datree@v1.0.0
        with:
          path: ./kubernetes/*.yml
        env:
          DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 
